### ISSUE TITLE
Only 3 minute screen recording time 

### ISSUE THREAD

**Issue by ghost** [muandrew/androidtool-mac#14]
If possible please increase the recording time upto 2 hours

**Comment by muandrew** [comment]
I'm not sure how well its going to work for up to two hours. You can try https://github.com/Genymobile/scrcpy which may support what you need.

**Comment by muandrew** [comment]
Ok I read the documentation again, this tool isn't going to support recording past 3 min anytime soon since this relies on adb and there is a max of 3 min for adb

https://developer.android.com/studio/command-line/adb
`--time-limit time | Sets the maximum recording time, in seconds. The default and maximum value is 180 (3 minutes).`
